version: "3.3"

services:
  mongodb:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_DATABASE=app-db
      - MONGO_INITDB_USERNAME=johnny
      - MONGO_INITDB_PASSWORD=appleseed
    volumes:
      - ./.mongo:/data/db
    ports:
      - '27017-27019:27017-27019'
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - 6379:6379